const SESSIONS = [
  {
    id: 1,
    title: "第1回 ガイダンス",
    questions: [
      { id: 1, text: "「コロナ禍」を起こしたウイルスの名前は，COVID-19である。", correct: false, explanation: "ウイルスの名前はSARS-CoV-2。COVID-19は疾患名。" },
      { id: 2, text: "コロナウイルスは，エンベロープを持っているウイルスである。", correct: true, explanation: "" },
      { id: 3, text: "ノロウイルスの無効化には，エタノールが有効である。", correct: false, explanation: "ノロウイルスにエタノールは効かない（ノンエンベロープウイルス）。" },
      { id: 4, text: "すべてのタンパク質は，20種類の標準アミノ酸から出来上がっている。", correct: true, explanation: "" },
      { id: 5, text: "DNAとは，デオキシリボ核酸のことである。", correct: true, explanation: "" },
      { id: 6, text: "DNAは二重らせん構造で，A（アデニン）の向かい側は必ずT（チミン）である。", correct: true, explanation: "" },
      { id: 7, text: "DNAの情報をmRNAに書き出すことを翻訳という。", correct: false, explanation: "DNAの情報をmRNAに書き出すことは「転写」。「翻訳」はmRNAの情報からタンパク質を合成すること。" },
      { id: 8, text: "翻訳の開始コドンはAUGであり，メチオニンをコードしている。", correct: true, explanation: "" },
      { id: 9, text: "mRNAの塩基３つにつき，１つのアミノ酸または翻訳停止が指定される。", correct: true, explanation: "" },
      { id: 10, text: "エタノールの摂取による悪心，嘔吐の原因は，酢酸である。", correct: false, explanation: "原因は酢酸ではなくアセトアルデヒド。" },
      { id: 11, text: "ALDH2は，アセトアルデヒドを酢酸に代謝する酵素である。", correct: true, explanation: "" },
      { id: 12, text: "ALDH2をコードするDNA配列の１塩基が変化したために，活性の低いALDH2ができる。", correct: true, explanation: "" },
      { id: 13, text: "活性が低いALDH2を持っている人は，ヨーロッパに多い。", correct: false, explanation: "活性が低いALDH2を持つ人は日本（東アジア）に多い。" },
      { id: 14, text: "薬理学的には，毒と薬とは同じ意味である。", correct: true, explanation: "" },
      { id: 15, text: "「天然由来の物質が安全」というのは嘘である。", correct: true, explanation: "" },
    ]
  },
  {
    id: 2,
    title: "第2回 薬理学入門",
    questions: [
      { id: 1, text: "薬には，本来体が持っていない新しい機能を付け加える効能がある。", correct: false, explanation: "薬は新しい機能を付け加えるのではなく，生理機能を補い逸脱を正常範囲内に戻す。" },
      { id: 2, text: "「麻薬中毒」とは，麻薬が欲しくて仕方がない依存性のことである。", correct: false, explanation: "「麻薬中毒」は過量による呼吸抑制などの中毒症状を指す。依存症とは区別される。" },
      { id: 3, text: "全ての薬には，副作用がある。", correct: true, explanation: "" },
      { id: 4, text: "アゴニストとは，生理的活性物質と同じ働きをするもののことである。", correct: true, explanation: "" },
      { id: 5, text: "薬の効果が発現する速さは，内服薬の方が静脈注射よりも速い。", correct: false, explanation: "静脈注射の方が内服薬より速い。" },
      { id: 6, text: "薬の吸収は，主として胃で行われる。", correct: false, explanation: "薬の吸収は主として小腸で行われる。" },
      { id: 7, text: "内服した薬物は門脈からまず肝臓に入り，そこで初回通過効果を受ける。", correct: true, explanation: "" },
      { id: 8, text: "抗狭心症薬ニトログリセリンは急速投与が必要なので，直腸内投与を行う。", correct: false, explanation: "直腸内ではなく舌下投与を行う。" },
      { id: 9, text: "舌下錠にすることによって，初回通過効果の影響を避けることができる。", correct: true, explanation: "" },
      { id: 10, text: "チトクロームP450の基質特異性はとても低いため，様々な薬物を代謝できる。", correct: true, explanation: "" },
      { id: 11, text: "生物学的半減期ごとに同一用量を投与すると，5回目でほぼ定常状態に近くなる。", correct: true, explanation: "" },
      { id: 12, text: "小児は大人を小さくしたものだから，投与する薬の量は体重で計算すればよい。", correct: false, explanation: "小児は大人を小さくしたものではない。代謝・分布が異なるため単純な体重換算では不十分。" },
      { id: 13, text: "コカインなどの中枢興奮薬は，身体的依存を伴う。", correct: false, explanation: "コカインなどの中枢興奮薬は精神的依存を伴う（身体的依存は少ない）。" },
      { id: 14, text: "ニトログリセリン（たばこに含まれる）では精神的依存は起きない。", correct: false, explanation: "正しくはニコチン。ニコチンは精神的依存を起こす。" },
      { id: 15, text: "コカインは，覚せい剤取締法によって規制されている。", correct: false, explanation: "コカインは麻薬及び向精神薬取締法で規制されている。" },
    ]
  },
  {
    id: 3,
    title: "第3回 神経細胞",
    questions: [
      { id: 1, text: "神経細胞の外にはNa⁺が多く，中にはK⁺が多い。", correct: true, explanation: "" },
      { id: 2, text: "神経細胞が脱分極すると，K⁺が流入する。", correct: false, explanation: "脱分極時に流入するのはK⁺ではなくNa⁺。" },
      { id: 3, text: "有髄神経線維は髄鞘に覆われており，跳躍伝導がおこなわれている。", correct: true, explanation: "" },
      { id: 4, text: "感覚神経・運動神経には，最も伝導速度が遅い神経線維が使われている。", correct: false, explanation: "感覚神経・運動神経には最も伝導速度が速い神経線維（Aα線維など）が使われている。" },
      { id: 5, text: "シナプス小胞は前シナプスにあり，中には神経伝達物質が入っている。", correct: true, explanation: "" },
      { id: 6, text: "トランスポーターは，シナプス間隙に放出された神経伝達物質を分解する。", correct: false, explanation: "トランスポーターは神経伝達物質を再取り込みする。分解するのは酵素（例：AChE）。" },
      { id: 7, text: "再取り込みとは，シナプス間隙に放出された神経伝達物質が，再び前シナプスに回収されることである。", correct: true, explanation: "" },
      { id: 8, text: "神経伝達物質が結合すると特定のイオンを通過させるものが，代謝型受容体である。", correct: false, explanation: "イオンを直接通過させるのはイオンチャネル型受容体。代謝型受容体はGタンパク質を介して作用する。" },
      { id: 9, text: "ムスカリン性アセチルコリン受容体は，代謝型受容体である。", correct: true, explanation: "" },
      { id: 10, text: "アセチルコリンエステラーゼは，アセチルコリンを産生する酵素である。", correct: false, explanation: "アセチルコリンエステラーゼはアセチルコリンを分解する酵素。産生するのはコリンアセチルトランスフェラーゼ。" },
      { id: 11, text: "AMPA型グルタミン酸受容体は，高頻度の刺激が蓄積した時にCa²⁺を透過させる。", correct: false, explanation: "高頻度刺激でCa²⁺を透過させるのはNMDA型グルタミン酸受容体。" },
      { id: 12, text: "シナプス後膜に過分極を引き起こすのが抑制性シナプスであり，Cl⁻を透過させる。", correct: true, explanation: "" },
      { id: 13, text: "GABA受容体は，興奮性シナプスのはたらきを担う受容体である。", correct: false, explanation: "GABA受容体は抑制性シナプスのはたらきを担う。" },
      { id: 14, text: "フグ毒であるテトロドトキシンは，Naチャネルを阻害する。", correct: true, explanation: "" },
      { id: 15, text: "抗うつ剤は，シナプス間隙のセロトニンの量を減らす効果がある。", correct: false, explanation: "抗うつ剤（SSRI等）はシナプス間隙のセロトニンの量を増やす。" },
    ]
  },
  {
    id: 4,
    title: "第4回 中枢神経作用薬①",
    questions: [
      { id: 1, text: "海馬は運動の協調を司る部位である。", correct: false, explanation: "海馬は記憶の形成を司る。運動の協調は小脳。" },
      { id: 2, text: "親水性有機分子は，血液脳関門（BBB）を通過しやすい。", correct: false, explanation: "親水性分子はBBBを通過できない。通過しやすいのは脂溶性分子。" },
      { id: 3, text: "パーキンソン病の原因は，大脳に存在するセロトニン神経細胞の脱落による。", correct: false, explanation: "パーキンソン病の原因は中脳の黒質に存在するドパミン神経細胞の脱落による。" },
      { id: 4, text: "レボドパはドパミンの前駆物質であり，パーキンソン病の治療に使用される。", correct: true, explanation: "" },
      { id: 5, text: "統合失調症の原因の一つとして，ドパミンの欠乏が考えられている。", correct: false, explanation: "統合失調症の原因はドパミンの過剰（ドパミン仮説）と考えられている。" },
      { id: 6, text: "定型抗精神病薬クロルプロマジンには，乗り物酔いを抑える効果もある。", correct: false, explanation: "クロルプロマジンに乗り物酔いを抑える効果はない。" },
      { id: 7, text: "選択的セロトニン再取り込み阻害薬（SSRI）は，抗うつ薬として使用される。", correct: true, explanation: "" },
      { id: 8, text: "アルツハイマー病では，初期にエピソード記憶の脱落が見られる。", correct: true, explanation: "" },
      { id: 9, text: "海馬を手術で切除されたHM氏は，経路探索課題を解くことはできた。", correct: false, explanation: "HM氏は海馬切除後，新しいエピソード記憶を形成できず，経路探索課題を解くことはできなかった。" },
      { id: 10, text: "ドネペジルは，脳内のアセチルコリンを減らす薬である。", correct: false, explanation: "ドネペジルはアセチルコリンエステラーゼ阻害薬で，脳内のアセチルコリンを増やす。" },
      { id: 11, text: "GABAは，血液脳関門を通過することができない。", correct: true, explanation: "" },
      { id: 12, text: "Non REM睡眠とは，睡眠の80%程度を占め，夢を見ている期間のことである。", correct: false, explanation: "Non REM睡眠は脳全体が眠っている期間。夢を見るのはREM睡眠。" },
      { id: 13, text: "催眠薬としては，バルビツール酸系の方がベンゾジアゼピン系より安全性が高い。", correct: false, explanation: "ベンゾジアゼピン系の方がバルビツール酸系より安全性が高い。" },
      { id: 14, text: "ベンゾジアゼピン系催眠薬の作用機序は，GABA作用の抑制である。", correct: false, explanation: "ベンゾジアゼピン系はGABA作用の促進（GABA_A受容体に結合してCl⁻流入を促進）。" },
      { id: 15, text: "ベンゾジアゼピン系催眠薬は，強迫性障害にも効果がある。", correct: false, explanation: "強迫性障害へのベンゾジアゼピン系の効果は期待できない。" },
    ]
  },
  {
    id: 5,
    title: "第5回 中枢神経作用薬② 末梢神経作用薬①",
    questions: [
      { id: 1, text: "華岡青洲の開発した全身麻酔薬にはアトロピンが含まれていた。", correct: true, explanation: "" },
      { id: 2, text: "全身麻酔薬で，最初に抑制されるのは延髄である。", correct: false, explanation: "最初に抑制されるのは延髄ではなく大脳皮質。延髄は最後に抑制される（生命維持中枢のため）。" },
      { id: 3, text: "吸入麻酔薬は，Na⁺チャネルの立体構造を変化させ，神経細胞の活動を抑制する。", correct: true, explanation: "" },
      { id: 4, text: "モルヒネの副作用として，下痢や散瞳があげられる。", correct: false, explanation: "モルヒネの副作用は便秘や縮瞳（下痢・散瞳は逆）。" },
      { id: 5, text: "交感神経の効果器ではアセチルコリン，副交感神経の効果器ではノルアドレナリンを使っている。", correct: false, explanation: "逆。交感神経の効果器ではノルアドレナリン，副交感神経の効果器ではアセチルコリンを使う。" },
      { id: 6, text: "交感神経の興奮で，心機能の亢進・気管支の拡張・消化管運動の亢進が起きる。", correct: false, explanation: "交感神経の興奮で消化管運動は亢進ではなく抑制される。" },
      { id: 7, text: "拡張期血圧が，最高血圧のことである。", correct: false, explanation: "最高血圧は収縮期血圧。拡張期血圧は最低血圧。" },
      { id: 8, text: "イソプレナリンは，β受容体よりもα受容体に親和性が高い。", correct: false, explanation: "イソプレナリンはα受容体よりもβ受容体に親和性が高い。" },
      { id: 9, text: "静注（点滴）した場合，ノルアドレナリンはイソプレナリンよりも拡張期血圧を下げる。", correct: false, explanation: "ノルアドレナリンはα作用により血管収縮・血圧上昇をもたらす。拡張期血圧を下げるのはイソプレナリン（β₂作用で末梢血管拡張）。" },
      { id: 10, text: "平滑筋については，α₁受容体の刺激が収縮，β₂受容体の刺激が弛緩にはたらく。", correct: true, explanation: "" },
      { id: 11, text: "α受容体の刺激により心機能が亢進する。", correct: false, explanation: "心機能を亢進させるのはβ₁受容体の刺激。" },
      { id: 12, text: "気管支筋は，β₂受容体を刺激すると収縮する。", correct: false, explanation: "気管支筋のβ₂受容体を刺激すると弛緩（気管支拡張）する。" },
      { id: 13, text: "エフェドリンはアドレナリン作用薬であり，気管支拡張作用がある。", correct: true, explanation: "" },
      { id: 14, text: "麦角アルカロイドはα受容体の遮断薬であり，かっては堕胎などにも用いられた。", correct: true, explanation: "" },
      { id: 15, text: "プロプラノロールには血圧を下げる効果があるが，気管支喘息患者には禁忌である。", correct: true, explanation: "" },
    ]
  },
  {
    id: 6,
    title: "第6回 末梢神経作用薬②",
    questions: [
      { id: 1, text: "副交感神経の興奮で，消化管運動の亢進・瞳孔の縮小・腺分泌の亢進が起きる。", correct: true, explanation: "" },
      { id: 2, text: "アセチルコリンエステラーゼ（AChE）は，アセチルコリン（ACh）を合成する酵素である。", correct: false, explanation: "AChEはAChを分解する酵素。合成するのはコリンアセチルトランスフェラーゼ。" },
      { id: 3, text: "ムスカリン性受容体作用薬は，腸管麻痺や緑内障の治療に用いられる。", correct: true, explanation: "" },
      { id: 4, text: "ムスカリン性受容体作用薬は，気管支喘息や胃潰瘍の治療に用いられる。", correct: false, explanation: "ムスカリン性受容体作用薬は気管支喘息や胃潰瘍には禁忌。" },
      { id: 5, text: "農薬やサリンは，コリンエステラーゼを活性化させる薬である。", correct: false, explanation: "農薬やサリンはコリンエステラーゼを阻害する（活性化ではない）。" },
      { id: 6, text: "アトロピンによって，縮瞳や心拍数の低下が起き，死に至ることもある。", correct: false, explanation: "アトロピンは抗コリン薬なので散瞳・心拍数増加をもたらす（縮瞳・心拍低下は逆）。" },
      { id: 7, text: "アトロピンは緑内障の患者には禁忌である。", correct: true, explanation: "" },
      { id: 8, text: "フィゾスチグミンは第三級アミンなので中枢作用がない。", correct: false, explanation: "第三級アミンはBBBを通過できるため中枢作用がある。" },
      { id: 9, text: "ネオスチグミンは第四級アンモニウムなので血液脳関門を通過しない。", correct: true, explanation: "" },
      { id: 10, text: "ほとんどの効果器は副交感神経による支配が優位で，例外は血管と汗腺とである。", correct: true, explanation: "" },
      { id: 11, text: "散瞳させるためには，抗コリン薬が有効である。", correct: true, explanation: "" },
      { id: 12, text: "神経筋接合部遮断薬は，骨格筋の収縮を起こす。", correct: false, explanation: "神経筋接合部遮断薬は骨格筋を弛緩させる（収縮ではなく遮断）。" },
      { id: 13, text: "クラーレを塗った矢によって狩られた動物を食しても，中毒を起こさない。", correct: true, explanation: "" },
      { id: 14, text: "局所麻酔薬では，運動神経の方が自律神経より先に麻痺する。", correct: false, explanation: "局所麻酔薬では自律神経の方が運動神経より先に麻痺する。" },
      { id: 15, text: "コカインは，局所麻酔薬として使用されることがある。", correct: true, explanation: "" },
    ]
  },
  {
    id: 7,
    title: "第7回 危険ドラッグ等",
    questions: [
      { id: 1, text: "報酬系が働くとき，側坐核から腹側被蓋野へとドパミンが放出される。", correct: false, explanation: "逆。腹側被蓋野（VTA）から側坐核へドパミンが放出される。" },
      { id: 2, text: "乱用薬物を摂取しただけで，報酬系が働いてしまう。", correct: true, explanation: "" },
      { id: 3, text: "大麻の作用は基本的に抑制性であり，幻覚をもたらす主成分はCBDである。", correct: false, explanation: "幻覚をもたらす主成分はCBDではなくTHC（テトラヒドロカンナビノール）。" },
      { id: 4, text: "新鮮な大麻草には，THCが大量に含まれている。", correct: false, explanation: "新鮮な大麻草にはTHCがほとんど含まれておらず，乾燥・加熱でTHCAが脱炭酸されTHCになる。" },
      { id: 5, text: "合成されたカンナビノイドは，麻薬及び向精神薬取締法で規制されている。", correct: true, explanation: "" },
      { id: 6, text: "麻薬の「麻」と大麻の「麻」とは，同じ由来の文字である。", correct: false, explanation: "「麻薬」の麻はアラビア語由来，「大麻」の麻は植物の麻（Cannabis）を指し，由来が異なる。" },
      { id: 7, text: "あへん法によると，どのような理由であっても，けしを栽培することはできない。", correct: false, explanation: "あへん法によれば，許可を得ればけしを栽培することができる。" },
      { id: 8, text: "危険ドラッグ対策で行われる緊急指定は，必ず審議会での手続きを経て行われる。", correct: false, explanation: "緊急指定は審議会を経ずに迅速に行うことができる制度。" },
      { id: 9, text: "トリカブトの毒は，カリウムチャネルが閉じるのを阻止する。", correct: false, explanation: "トリカブト（アコニチン）の毒はナトリウムチャネルを阻害（開放状態を維持）する。" },
      { id: 10, text: "シアン化水素は，かすかにビターアーモンドの匂いがする。", correct: true, explanation: "" },
      { id: 11, text: "シアン化合物は，ミトコンドリアの機能を阻害し，細胞内でのATP合成をストップさせる。", correct: true, explanation: "" },
      { id: 12, text: "\"Drinking the Kool-Aid\" という慣用句で出てくる「クールエイド」とは，トリカブトの毒が入った飲み物を指す。", correct: false, explanation: "ジョーンズタウン事件で使われた飲み物には青酸カリ（シアン化カリウム）が入っていた。" },
      { id: 13, text: "亜ヒ酸には，独特の苦味があるので，混入されてもすぐに気が付く。", correct: false, explanation: "亜ヒ酸は無色無臭で味もほとんどなく，混入されても気付きにくい。" },
      { id: 14, text: "タリウムの生体内での挙動は，カルシウムのそれに類似しており，カルシウム依存性の過程を阻害する。", correct: false, explanation: "タリウムの挙動はカルシウムではなくカリウムに類似している。" },
      { id: 15, text: "アジ化ナトリウムは，経口摂取しても胃酸と反応して水素が発生するだけなので，ほとんど人体に毒性はない。", correct: false, explanation: "胃酸と反応するとアジ化水素ガスが発生し，強い毒性がある。" },
    ]
  },
  {
    id: 8,
    title: "第8回 抗感染症薬・消毒薬",
    questions: [
      { id: 1, text: "動物細胞には細胞壁が存在しないが，感染を引き起こす細菌には細胞壁がある。", correct: true, explanation: "" },
      { id: 2, text: "ペニシリン系抗菌薬は，細菌のタンパク質の合成を阻害する。", correct: false, explanation: "ペニシリン系はタンパク質合成ではなく細胞壁合成を阻害する。" },
      { id: 3, text: "ストレプトマイシンは，核酸合成を阻害することにより抗菌力を発揮する。", correct: false, explanation: "ストレプトマイシン（アミノグリコシド系）はタンパク質合成を阻害する。" },
      { id: 4, text: "アミノグリコシド系抗菌薬は，第3脳神経障害を起こしやすい。", correct: false, explanation: "第3脳神経ではなく第8脳神経（聴神経）障害（難聴・前庭障害）を起こしやすい。" },
      { id: 5, text: "バンコマイシンはMRSAの治療薬の一つだが，最近，耐性菌が現れている。", correct: true, explanation: "" },
      { id: 6, text: "リファンピシンは結核の治療に用いられるが，青い化合物なので，尿や便・唾液・涙などが青色になる。", correct: false, explanation: "リファンピシンは赤い化合物であり，尿・便・涙などが赤橙色になる。" },
      { id: 7, text: "抗真菌薬は，真菌細胞膜にあるコレステロールに結合し，細胞膜機能を障害する。", correct: false, explanation: "真菌細胞膜にあるのはコレステロールではなくエルゴステロール。" },
      { id: 8, text: "逆転写酵素阻害薬はRNAウイルスの治療に使用される。", correct: true, explanation: "" },
      { id: 9, text: "病原微生物を感染症にならない程度まで死滅させることを，滅菌という。", correct: false, explanation: "感染症にならない程度まで死滅させることは「消毒」。「滅菌」はすべての微生物を死滅させること。" },
      { id: 10, text: "クロルヘキシジンは，ウイルスに効果がある。", correct: false, explanation: "クロルヘキシジンはウイルスには効果がない（細菌に有効）。" },
      { id: 11, text: "ポピドンヨードは皮膚・粘膜などの消毒に適している。", correct: true, explanation: "" },
      { id: 12, text: "次亜塩素酸ナトリウムは，金属の消毒に用いられる。", correct: false, explanation: "次亜塩素酸ナトリウムは腐食性があるため金属の消毒には用いない。" },
      { id: 13, text: "次亜塩素酸ナトリウムは，ウイルスに効果がある。", correct: true, explanation: "" },
      { id: 14, text: "消毒用エタノールとは，100%アルコール（99.5%アルコール）のことである。", correct: false, explanation: "消毒用エタノールは70%アルコール。100%では効果が低下する。" },
      { id: 15, text: "ノロウイルスには，消毒用エタノールは有効である。", correct: false, explanation: "ノロウイルスはノンエンベロープウイルスのためエタノールは無効。次亜塩素酸ナトリウムが有効。" },
    ]
  },
  {
    id: 9,
    title: "第9回 呼吸器系・循環器系作用薬",
    questions: [
      { id: 1, text: "ヘモグロビン１分子は，２分子の酸素と結合できる。", correct: false, explanation: "ヘモグロビン1分子には4つのサブユニットがあり，4分子の酸素と結合できる。" },
      { id: 2, text: "組織では，低酸素状態で酸素飽和度が低下しても，血中酸素分圧は低く保たれる。", correct: false, explanation: "低酸素状態では血中酸素分圧も低下する（低く保たれるのではなく低下する）。" },
      { id: 3, text: "血液のpH低下やCO₂増加は，ヘモグロビンから酸素を離れやすくさせる。", correct: true, explanation: "" },
      { id: 4, text: "頸動脈小体にはCO₂の分圧センサーがある。", correct: false, explanation: "頸動脈小体は主にO₂の分圧センサー。CO₂・pHの中枢センサーは延髄の腹側にある。" },
      { id: 5, text: "肺静脈は，心臓の右心室から肺に向かう血管で，静脈血が流れている。", correct: false, explanation: "肺静脈は肺から左心房へ向かう血管で，動脈血（酸素化された血液）が流れている。右心室から肺へは肺動脈。" },
      { id: 6, text: "高カリウム血症では，心電図においてT波が増高し，テント状となる。", correct: true, explanation: "" },
      { id: 7, text: "副腎皮質ステロイド薬は，気管支喘息の治療薬として使用される。", correct: true, explanation: "" },
      { id: 8, text: "テオフィリンは，cAMPの合成を促進することで，気管支を拡張させる。", correct: false, explanation: "テオフィリンはホスホジエステラーゼ（PDE）を阻害してcAMPの分解を抑制する（合成促進ではない）。" },
      { id: 9, text: "コデインは，咳反射の中枢である延髄に作用して，鎮咳効果をもたらす。", correct: true, explanation: "" },
      { id: 10, text: "ジギタリスは，Na⁺, K⁺－ATPアーゼの働きを増強する。", correct: false, explanation: "ジギタリスはNa⁺/K⁺-ATPアーゼを阻害（抑制）する。" },
      { id: 11, text: "アンギオテンシンII受容体の拮抗薬は，血管拡張薬として使われる。", correct: true, explanation: "" },
      { id: 12, text: "有機硝酸エステルは，狭心症発症時の第一選択薬で，体内でCO₂を放出する。", correct: false, explanation: "有機硝酸エステルは体内でNO（一酸化窒素）を放出する（CO₂ではない）。" },
      { id: 13, text: "摂取するNaClの量が恒常的に多いと，体に貯留される水分が増加し，血圧が上がる。", correct: true, explanation: "" },
      { id: 14, text: "アンギオテンシンIIは，ACEによって分解され，アンギオテンシンIになる。", correct: false, explanation: "ACEはアンギオテンシンI→IIに変換する酵素。IIがACEで分解されてIになるのは逆。" },
      { id: 15, text: "Ca²⁺チャネル遮断薬は高価なので，高血圧の治療薬としては使われていない。", correct: false, explanation: "Ca²⁺チャネル遮断薬（カルシウム拮抗薬）は利尿薬に次いで安価で，高血圧の第一選択薬として広く使われている。" },
    ]
  },
  {
    id: 10,
    title: "第10回 消化器系の生化学，生理学",
    questions: [
      { id: 1, text: "結腸は，大腸の一部である。", correct: true, explanation: "" },
      { id: 2, text: "デンプンは，最終的に胃で消化されて単糖になる。", correct: false, explanation: "胃ではなく小腸で消化されて単糖になる。" },
      { id: 3, text: "タンパク質は，胃で最初に消化を受ける。", correct: true, explanation: "" },
      { id: 4, text: "唾液の分泌や消化活動は，視床下部によって活性化される。", correct: true, explanation: "" },
      { id: 5, text: "ペプシンはペプシノーゲンという形で酸分泌細胞から分泌される。", correct: false, explanation: "酸分泌細胞ではなく主細胞から分泌される。" },
      { id: 6, text: "胃酸の作用は，殺菌作用だけである。", correct: false, explanation: "殺菌作用だけでなく，ペプシノーゲン（不活性）をペプシン（活性型）に変換したり，タンパク質の立体構造を変えてペプシンの作用を受けやすくするなどの作用もある。" },
      { id: 7, text: "胃は，粘液やHCO₃⁻によって保護されている。", correct: true, explanation: "" },
      { id: 8, text: "直腸には微絨毛という構造があり，そこで栄養が吸収されている。", correct: false, explanation: "直腸ではなく小腸（小腸壁）に微絨毛があり，そこで栄養が吸収されている。" },
      { id: 9, text: "糖やアミノ酸は大腸で吸収される。", correct: false, explanation: "糖やアミノ酸は大腸ではなく小腸（空腸から回腸）で吸収される。" },
      { id: 10, text: "唾液アミラーゼは，でんぷんやグリコーゲンを基質とする。", correct: true, explanation: "" },
      { id: 11, text: "膵液には，多くの酵素が含まれており，でんぷんやグリコーゲン，タンパク質，中性脂肪を基質とする酵素などが含まれている。", correct: true, explanation: "" },
      { id: 12, text: "炭水化物は，最終的にアミノ酸にまで分解されて，栄養として吸収される。", correct: false, explanation: "炭水化物は最終的にアミノ酸ではなく単糖にまで分解されて吸収される（アミノ酸はタンパク質の最終分解産物）。" },
      { id: 13, text: "脂質は，胆汁酸とリン脂質とによって乳化される。", correct: true, explanation: "" },
      { id: 14, text: "ビタミンB₁₂（コバラミン）は，組織に供給されるとともに，肝臓に蓄えられる。", correct: true, explanation: "" },
      { id: 15, text: "植物ヒマから作られるリシンは，人類史上，最も毒性が強い物質の一つである。", correct: true, explanation: "" },
    ]
  },
  {
    id: 11,
    title: "第11回 消化器系作用薬",
    questions: [
      { id: 1, text: "制酸薬は胃酸を中和する薬であり、胃の中がpH7程度になるように服用する。", correct: false, explanation: "胃の中がpH7ではなく，pH4〜4.5程度になるようにする。" },
      { id: 2, text: "ヒスタミンH2遮断薬は、胃酸の分泌を抑制する。", correct: true, explanation: "" },
      { id: 3, text: "糖尿薬に使われる生薬は、甘い。", correct: false, explanation: "甘いではなく苦い生薬が使われる。" },
      { id: 4, text: "ドパミンD2受容体拮抗薬は、胃運動を促進する。", correct: true, explanation: "" },
      { id: 5, text: "化学受容器引金帯（CTZ）には、ドパミンD2受容体、セロトニン5-HT3受容体が存在する。", correct: true, explanation: "" },
      { id: 6, text: "セロトニン5HT3遮断薬は、抗がん剤による吐き気や乗り物酔いに効き目がある。", correct: false, explanation: "セロトニン5-HT3遮断薬は抗がん剤による吐き気に効果があるが，乗り物酔いには効果はない。" },
      { id: 7, text: "ヒスタミンH2遮断薬は、乗り物酔いに効果がある。", correct: false, explanation: "乗り物酔いに効果があるのはH2遮断薬ではなくH1遮断薬（抗ヒスタミン薬）。" },
      { id: 8, text: "トウゴマの種子から採取されるヒマシ油は、下剤として使われる。", correct: true, explanation: "" },
      { id: 9, text: "ビスマスの化合物は、腸を保護する目的で収斂薬として使用される。", correct: true, explanation: "" },
      { id: 10, text: "酒石酸抑薬（催吐薬）はアルコールの分解を抑制し、気分を悪くさせる。", correct: false, explanation: "アルコールではなくアセトアルデヒドの分解を抑制し，気分を悪くさせる。" },
      { id: 11, text: "非ステロイド抗炎症薬には、胃粘膜を保護する効果がある。", correct: false, explanation: "非ステロイド抗炎症薬（NSAIDs）は胃粘膜を保護するのではなく，胃粘膜障害を起こす。" },
      { id: 12, text: "アスピリンは、アセチルサリチル酸のことである。", correct: true, explanation: "" },
      { id: 13, text: "アスピリンは、毒性が比較的強いので、日常的な解熱、鎮痛薬としては使わない。", correct: false, explanation: "アスピリンは日常的な解熱・鎮痛薬として使われる。毒性が比較的強く日常使用しないのはインドメタシン。" },
      { id: 14, text: "ステロイド抗炎症薬には免疫抑制作用があり、感染症の増悪という副作用もある。", correct: true, explanation: "" },
      { id: 15, text: "ステロイド抗炎症薬の副作用の一つとして、骨粗鬆症がある。", correct: true, explanation: "" },
    ]
  },

];
